---
# Ref: https://help.github.com/en/github/building-a-strong-community/configuring-issue-templates-for-your-repository#configuring-the-template-chooser
blank_issues_enabled: true  # default
contact_links:
  - name: ğŸ” Security bug report ğŸ”¥
    url: https://github.com/imjoseangel/open-source-contribution?utm_medium=github&utm_source=issue_template_chooser
    about: |
      Please learn how to report security vulnerabilities here.

      For all security related bugs, email josea.munoz@gmail.com
      instead of using this issue tracker and you will receive
      a prompt response.

      For more information, see
      https://github.com/imjoseangel/open-source-contribution
  - name: ğŸ“ Code of Conduct
    url: https://github.com/imjoseangel/open-source-contribution/blob/devel/.github/CODE_OF_CONDUCT.md
    about: â¤ Be nice to other members of the community. â˜® Behave.
  - name: ğŸ’¬ Talks to the community
    url: https://github.com/imjoseangel/open-source-contribution?utm_medium=github&utm_source=issue_template_chooser#mailing-list-information
    about: Please ask and answer usage questions here
  - name: âš¡ Working groups
    url: https://github.com/imjoseangel/open-source-contribution/wiki
    about: Interested in improving a specific area? Become a part of a working group!
